# Generated by Django 2.2.6 on 2019-10-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('horario_func', models.TextField()),
                ('idade_minima', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='atracoes')),
            ],
            options={
                'db_table': 'atracoes',
                'managed': True,
            },
        ),
    ]
