# Generated by Django 2.2.6 on 2019-10-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocIdentificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PontoTuristicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pontos_turisticos')),
                ('atracoes', models.ManyToManyField(to='atracoes.Atracoes')),
                ('avaliacoes', models.ManyToManyField(to='avaliacoes.Avaliacoes')),
                ('comentarios', models.ManyToManyField(to='comentarios.Comentarios')),
                ('doc_identificacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DocIdentificacao')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Endereco')),
            ],
            options={
                'db_table': 'pontos_turisticos',
                'managed': True,
            },
        ),
    ]
