# Generated by Django 2.2.5 on 2019-10-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0002_auto_20190928_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturisticos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentarios'),
        ),
        migrations.AlterField(
            model_name='pontoturisticos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracoes'),
        ),
    ]
